a ="Poonam"
print(len(a))
print(a.upper())
print(a.lower())
print(a.capitalize())
b= "!!!jPoonam!!"
print(b.rstrip("!"))
print(a.replace("Poonam", "Pooh"))
print(a.split("o"))
print(a.split("m"))
print(a.center(50))
print(a.count("Poonam"))
print(a.endswith("am",0,6))
print(a.find("o"))
print(a.find("m"))
print(a.index("m"))
print(a.isalpha())
print(a.isalnum())
print(b.isalpha())
print(b.isalnum())
print(a.isdigit()) 
c="Poonam is a good girl.\n"
print(c)
print(c.swapcase())
print(c.isprintable())
print(c.isspace())
print(c.title())
print(c.istitle())
d="     "
print(d.isspace())
